export const
    LOGIN_HAS_ERRORED = 'LOGIN_HAS_ERRORED',
    IS_LOGIN = 'IS_LOGIN',
    SAVE_MY_BOARDS = 'SAVE_MY_BOARDS',
    SAVE_INVAIT_BOARD = 'SAVE_INVAIT_BOARD',
    SAVE_SECRET = 'SAVE_SECRET',
    SAVE_MY_BACKLOG_TASKS = 'SAVE_MY_BACKLOG_TASKS',
    SAVE_MY_DONE_TASKS = 'SAVE_MY_DONE_TASKS',
    SAVE_MY_TODO_TASKS = 'SAVE_MY_TODO_TASKS',
    SAVE_USERS = 'SAVE_USERS',
    CLEAR_USERS = 'CLEAR_USERS',
    URL = 'http://localhost:3000/api';
    